### PR TITLE
cors

### PR DESCRIPTION
**Pull request by mejamiewilson**

### CODE REVIEW

**Comment by mejamiewilson** [comment]
I can't seem to work out how to test this - and let me know if it's a security concern - but someone in Intercom wanted it :) (I guess it makes testing or raising your own events much simpler)

**Comment by buildmaster** [comment]
my concern with this is that we shouldn't be encouraging front end access via the API direct. The API keys arent' secure for that. They have no sense of permissions, or being able to regenerate or anything really. So once your API key is out in the wild anyone can use it to access your event stream and any sense of privacy/security is gone. Not to do with CORS specifically but the API key in front end JavaScript is a BAD idea

**Comment by mejamiewilson** [comment]
We can add that security in later if need be, but we have a customer who wants to do it, i'm not sure in what context but I think we should just allow it.

**Comment by buildmaster** [comment]
it's on your head

**Pull request merged**
